### ISSUE TITLE
特性请求 - 虚幻骨架指Rigify的FK控制器的模板

### ISSUE THREAD

**Issue by Eragon-Brisingr** [kumopult/blender_BoneAnimCopy#1]
在尝试该插件时我选择将虚幻的骨骼重定向至Blender的Rigify控制器上，但是测试中重定向胯关节的位移时由于是使用世界空间映射的位置会发生错误的偏移。

![image](https://user-images.githubusercontent.com/16950908/99952614-df646e00-2dba-11eb-8890-4dfec614596c.png)
![image](https://user-images.githubusercontent.com/16950908/99952631-e5f2e580-2dba-11eb-9e92-78ea016c3c6a.png)

**Comment by kumopult** [comment]
看这操作是想让rigfy控制器去模仿ue4骨骼的动作么？
这插件目前确实是只考虑了形变骨-形变骨的重定向，并没有考虑形变骨-控制器的情况。。
只映射世界空间确实是目前的局限，我现在一般是靠缩放动作源骨架来适配大小
如果想改成局部坐标映射来适配的话可以在骨骼约束面板展开BAC_LOCCOPY来手动修改，不过一旦涉及到这一层的话处理方法就非常多变了，我感觉打包成插件的批处理形式反而会更绕。。

**Comment by Eragon-Brisingr** [comment]
嗯，是的。我在尝试将虚幻的骨骼重定向至rigify，局部的适配还挺必要的。假如这个插件现在是没法支持的话我自己去写点脚本跑批处理吧，谢谢了。
