### ISSUE TITLE
希望大佬能做一个批量烘焙动画的功能

### ISSUE THREAD

**Issue by DTEX123** [kumopult/blender_BoneAnimCopy#3]
如果可以的话新动画的名称希望能把默认的action改成其他的，比如加一段或删一段自定义语句什么的

**Comment by kumopult** [comment]
这个在计划中，不过还得找点参考。。
一方面，fbx动作导入时骨架会命名为root之类的固定名称而不是文件名，得手动修改，这一点我在想有没有可能手动封装一个导入功能来处理。如果发现有关于fbx导入的插件务必告诉我
导入之后的话，就可以用一个集合来存放所有动作骨架然后遍历。比较麻烦的是需要逐一判断每一个骨架动作的长度来调整烘培帧数。。相关的接口我也没了解过，还有待实验
