### ISSUE TITLE
插件初始状态下，按F3会使控制台报错

### ISSUE THREAD

**Issue by OTOMariK** [kumopult/blender_BoneAnimCopy#5]
初始状态下，插件的映射骨架为空。此时按F3（不需要执行任何命令，仅仅是列出所有可用的Operator），控制台会输出如下信息

> Traceback (most recent call last):
>   File ".\BoneAnimCopy\mapping.py", line 302, in poll
>     s = get_state()
>   File ".\BoneAnimCopy\utilfuncs.py", line 4, in get_state
>     return bpy.context.scene.kumopult_bac_owner.data.kumopult_bac
> AttributeError: 'NoneType' object has no attribute 'data'
> Traceback (most recent call last):
>   File ".\BoneAnimCopy\mapping.py", line 384, in poll
>     s = get_state()
>   File ".\BoneAnimCopy\utilfuncs.py", line 4, in get_state
>     return bpy.context.scene.kumopult_bac_owner.data.kumopult_bac
> AttributeError: 'NoneType' object has no attribute 'data'
> Traceback (most recent call last):
>   File ".\BoneAnimCopy\mapping.py", line 346, in poll
>     s = get_state()
>   File ".\BoneAnimCopy\utilfuncs.py", line 4, in get_state
>     return bpy.context.scene.kumopult_bac_owner.data.kumopult_bac
> AttributeError: 'NoneType' object has no attribute 'data'

看起来blender在列出所有可用的Operator之前会执行所有Operator的poll()

**Comment by kumopult** [comment]
None类报错还真是容易漏网。。
