### ISSUE TITLE
不知道为啥3.6启用不了

### ISSUE THREAD

**Issue by BUGProtectionAssociation** [kumopult/blender_BoneAnimCopy#7]
提示这东西

```
Traceback (most recent call last):
  File "G:\blender\36\3.6\scripts\modules\addon_utils.py", line 333, in enable
    mod = __import__(module_name)
ModuleNotFoundError: No module named 'blender_BoneAnimCopy-1'
```
找不到blender_BoneAnimCopy-1这个模块

![image](https://user-images.githubusercontent.com/65578116/236677048-ca5203f9-baa7-49a4-b3a9-c86f446b530c.png)

**Comment by kumopult** [comment]
我在插件面板用右上角安装没有这个问题。这报错结尾的-1看起来对应的是你的文件夹名称中的-1.0，手动重命名一下，把-1.0去掉试试？

**Comment by BUGProtectionAssociation** [comment]
> 我在插件面板用右上角安装没有这个问题。这报错结尾的-1看起来对应的是你的文件夹名称中的-1.0，手动重命名一下，把-1.0去掉试试？

下次更新时，压缩文件里面插件文件夹不要带版本号，只给打包到压缩文件本身加版本号
